package tw.sysbase.entity.pub;


/**
 * ObjAttribute generated by hbm2java
 */
public class ObjAttributeVo {

	private String id;
	private String objId;
	private String code;
	private String name;
	private Integer sysFlag;
	
	private String column;
	private Integer pkFlag;
	private String classType;
	private Integer order;
	private Integer allowBlank;
	private String verifyRule;
	private String createTime;
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getObjId() {
		return objId;
	}
	public void setObjId(String objId) {
		this.objId = objId;
	}
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public Integer getSysFlag() {
		return sysFlag;
	}
	public void setSysFlag(Integer sysFlag) {
		this.sysFlag = sysFlag;
	}
	public String getColumn() {
		return column;
	}
	public void setColumn(String column) {
		this.column = column;
	}
	public Integer getPkFlag() {
		return pkFlag;
	}
	public void setPkFlag(Integer pkFlag) {
		this.pkFlag = pkFlag;
	}
	public String getClassType() {
		return classType;
	}
	public void setClassType(String classType) {
		this.classType = classType;
	}
	public Integer getOrder() {
		return order;
	}
	public void setOrder(Integer order) {
		this.order = order;
	}
	public Integer getAllowBlank() {
		return allowBlank;
	}
	public void setAllowBlank(Integer allowBlank) {
		this.allowBlank = allowBlank;
	}
	public String getVerifyRule() {
		return verifyRule;
	}
	public void setVerifyRule(String verifyRule) {
		this.verifyRule = verifyRule;
	}
	public String getCreateTime() {
		return createTime;
	}
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}
}
