package tw.sysbase.entity.pub;


/**
 * ObjType generated by hbm2java
 */
public class ObjType {

	private String id;
	private String code;
	private String name;
	private String typeCate;
	private Integer sysFlag;
	private String defaultValue;
	private Integer defaultLength;
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getTypeCate() {
		return typeCate;
	}
	public void setTypeCate(String typeCate) {
		this.typeCate = typeCate;
	}
	public Integer getSysFlag() {
		return sysFlag;
	}
	public void setSysFlag(Integer sysFlag) {
		this.sysFlag = sysFlag;
	}
	public String getDefaultValue() {
		return defaultValue;
	}
	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}
	public Integer getDefaultLength() {
		return defaultLength;
	}
	public void setDefaultLength(Integer defaultLength) {
		this.defaultLength = defaultLength;
	}
}
