package tw.sysbase.entity.pub;

// Generated by mars

/**
 * 
 */
public class TypeRefDic {

	private String id;
	private String objEntityRefId;
	private String parentId;
	private String childId;
	private Integer sysFlag;
	private Integer order;
	private String createTime;
	
	//业务属性
	private String objEntityRefName;
	private String parentName;
	private String parentTypeCode;
	private String childName;
	private String childTypeCode;
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	public String getObjEntityRefId() {
		return objEntityRefId;
	}
	public void setObjEntityRefId(String objEntityRefId) {
		this.objEntityRefId = objEntityRefId;
	}
	public String getParentId() {
		return parentId;
	}
	public void setParentId(String parentId) {
		this.parentId = parentId;
	}
	public String getChildId() {
		return childId;
	}
	public void setChildId(String childId) {
		this.childId = childId;
	}
	public Integer getSysFlag() {
		return sysFlag;
	}
	public void setSysFlag(Integer sysFlag) {
		this.sysFlag = sysFlag;
	}
	public Integer getOrder() {
		return order;
	}
	public void setOrder(Integer order) {
		this.order = order;
	}
	public String getCreateTime() {
		return createTime;
	}
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}
	public String getObjEntityRefName() {
		return objEntityRefName;
	}
	public void setObjEntityRefName(String objEntityRefName) {
		this.objEntityRefName = objEntityRefName;
	}
	public String getParentName() {
		return parentName;
	}
	public void setParentName(String parentName) {
		this.parentName = parentName;
	}
	public String getChildName() {
		return childName;
	}
	public void setChildName(String childName) {
		this.childName = childName;
	}
	public String getParentTypeCode() {
		return parentTypeCode;
	}
	public void setParentTypeCode(String parentTypeCode) {
		this.parentTypeCode = parentTypeCode;
	}
	public String getChildTypeCode() {
		return childTypeCode;
	}
	public void setChildTypeCode(String childTypeCode) {
		this.childTypeCode = childTypeCode;
	}
	
}
