var request = talkweb.ControlBus.getRequest();
talkweb.Bus.ready({
	items:[
	{
		classPath:"Components.Form",
		options:{
			id:"sendmsginfoform",
			name:"sendmsginfoform",
			container:"sendmsginfoform",
			dataSource:"msg_getMsgSendInfo.action?SENDMSGID="+request['sendmsgid'],
			saveInstance:true,
			haveSubmitBtn: false, //是否有提交按钮
            haveResetBtn: false, //是否有重置按钮
            submitCallback: function(result){
                alert(result.msg);
            },
            items : [
            {
            	classPath:"BaseControl.Label",
            	width:"100%",
            	options:{
            		name:"msgname",
            		notes:"消息主题：",
            		id:"msgname"
            	}
            },{
            	classPath:"BaseControl.Label",
            	width:"100%",
            	options:{
            		name:"sendhuman",
            		notes:"发送人：",
            		id:"sendhuman"
            	}
            },{
            	classPath:"BaseControl.Label",
            	options:{
            		name:"accepthuman",
            		notes:"发送对象：",
            		id:"accepthuman"
            	}
            },{
            	classPath:"BaseControl.Label",
            	options:{
            		name:"msgtype",
            		notes:"消息类型：",
            		id:"msgtype"
            	}
            },{
            	classPath:"BaseControl.Label",
            	options:{
            		name:"msgmodel",
            		notes:"选择模板：",
            		id:"msgmodel"
            	}
            },{
            	classPath:"BaseControl.Label",
            	options:{
            		name:"sendtypemsg",
            		notes:"通知方式：",
            		id:"sendtypemsg"
            	}
            },{
            	classPath:"BaseControl.Label",
            	options:{
            		name:"senddate",
            		notes:"发送时间：",
            		id:"senddate"
            	}
            },{
            	classPath:"BaseControl.Label",
            	options:{
            		name:"msgcontent",
            		notes:"消息内容：",
            		id:"msgcontent"
            	}
            }
            ]
		}
	},{
		classPath:"BaseControl.Button",
		options:{
			value:"关闭",
			container:"buttons",
			click:function(){
				window.parent.dialog.close();
			}
		}
	}
	]
});